### ISSUE TITLE
Use flexbox to center vertically

### ISSUE THREAD

**Issue by rodfersou** [ismamz/postcss-utilities#10]
Isn't it better to use flexbox to center vertically?

**Comment by ismamz** [comment]
Yes! We could have that option.

```css
.parent {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

All elements within the parent block will be centered vertically. Do you think it is good?

We have to resolve how call the different methods. Maybe in the plugin configuration you can set:
`{ "centerMethod": "flexbox" }`

[`text-hide`](https://ismamz.github.io/postcss-utilities/docs#text-hide) has an alternative technique too, and I think the naming isn't fine. We could extend the idea of define alternative methods in the configuration.
