### ISSUE TITLE
more customization to `hr`

### ISSUE THREAD

**Issue by revyh** [ismamz/postcss-utilities#13]
How about adding `height` and `style` arguments to hr?

```css
/* signature: hr( [color], [vertical-margin], [style], [height] ) */
/* defaults: style = solid, height = 1px

/* before */
hr {
  @util hr(#000, 20px, dashed, 10px);
}

/* after */
hr {
  height: 0;
  border: 0;
  border-top: 10px dashed #000;
  margin: 20px 0;
  display: block;
}
```
