### ISSUE TITLE
Add max/min to size utility

### ISSUE THREAD

**Issue by foubei** [ismamz/postcss-utilities#18]
Hello, it will be better if you can add **max**/**min** size for both **width** and **height** to the size shortcut or even create new shortcuts like min-size and max-size something like what they did here in this plugin [postcss-short-size](https://github.com/jonathantneal/postcss-short-size).
Thanks

**Comment by ismamz** [comment]
Hello! Yes, It's a nice option. I'll added to the list for the next version.
```css
/* before */
.selector {
  @util min-size(100px, 50px);
}

/* after */
.selector {
  min-width: 100px;
  max-height: 50px;
}
```
Thanks for the suggestion and I hope to release the new version soon!
