### ISSUE TITLE
Documentation for @util circle output is incorrect

### ISSUE THREAD

**Issue by aarongeorge** [ismamz/postcss-utilities#28]
The output for @util circle is:

```css
.circle {
    height: 200px;
    width: 200px;
    border-radius: 50%;
    color: #268BD2;
}
```

Where `color` should be `background-color`
